config/routes.rb
Rails.application.routes.draw do
  root to: "root#root"
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  post "session/demo", to: "sessions#demo_user_sign_in"
  resources :queries, only: [:create]
  get "checkout", to: "checkouts#checkout"
  post "checkout/add_address", to: "checkouts#add_address"
  post "checkout/select_address", to: "checkouts#select_address"
  post "checkout/add_card", to: "checkouts#add_card"
  post "checkout/select_card", to: "checkouts#select_card"
  post "checkout/add_purchased_products", to: "checkouts#add_purchased_products"

  namespace :api, defaults: { format: :json } do
    get "current_user/show", to: "current_users#show"
    post "current_user/update", to: "current_users#update"
    get "current_user/cart", to: "current_users#cart"
    get "current_user/products", to: "current_users#products"
    get "current_user/purchased_products", to: "current_users#purchased_products"
    get "current_user/addresses", to: "current_users#addresses"
    get "current_user/current_address", to: "current_users#current_address"
    get "current_user/cards", to: "current_users#cards"
    resources :users, only: [:index, :show] do
      resources :products, only: [:new, :create, :show] do
        resources :reviews, only: [:index, :show, :new, :create]
      end
    end
    resources :queries, only: [:index]
    resources :cart_products, only: [:show, :index]
    post "/cart_products/add/:product_id", to: "cart_products#add_to_cart"
    delete "/cart_products/del/:product_id", to: "cart_products#delete_from_cart"
    patch "/cart_products/qty/:product_id", to: "cart_products#update_quantity"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 8, allow_nil: true }

  has_attached_file :picture,
                    styles: {
                      thumb: "65x65",
                      small: "100x100",
                      medium: "200x200",
                      large: "300x300"
                    },
                    default_url: "user_default_picture_:style.png"

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  attr_reader :password

  after_initialize :ensure_session_token!

  has_many(
    :products,
    class_name: "Product",
    foreign_key: :seller_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :queries,
    class_name: "Query",
    foreign_key: :querier_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_one(
    :cart,
    class_name: "Cart",
    foreign_key: :buyer_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :cart_products, through: :cart, source: :cart_products

  has_many(
    :addresses,
    class_name: "Address",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :purchases,
    class_name: "Purchase",
    foreign_key: :buyer_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :purchased_products, through: :purchases, source: :product

  has_many(
    :reviews,
    class_name: "Review",
    foreign_key: :reviewer_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many :reviewed_products, through: :reviews, source: :product

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil? || !user.valid_password?(password)

    return user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def default_shipping_address
    return nil unless self.default_shipping_address_id

    Address.find(self.default_shipping_address_id)
  end

  def current_shipping_address
    return nil unless self.current_shipping_address_id

    Address.find(self.current_shipping_address_id)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :created_at,
      :phone_number,
      :picture
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :phone_number,
      :password,
      :picture
    )
  end
end

app/views/users/new.html.erb
<header class="auth-header group">
  <ul>
    <li>
      <a href="/">
        <img class="logo"
             src="<%= image_url("hippolyta_logo_black.png") %>"
             alt="hippolyta logo" />
      </a>
    </li>

    <section class="links">
      <li>
        <a href="<%= new_session_url %>">
          Your Account
        </a>
      </li>
    </section>

  </ul>
</header>

<main class="auth-main">
  <%= (flash[:errors].join("<br>") + "<br>" + "<br>").html_safe if flash[:errors] %>

  <h2 class="auth-h2">Registration<h2>

  <form class="create-user group"
        action="<%= users_url %>"
        method="post">
    <%= authenticity_token %>

    <fieldset>
      <div class="auth-input group">
        <h3 class="auth-h3">New to Hippolyta.us? Register Below.</h3>
        <ul>
          <li>
            <label>My name is:</label>
            <input type="text"
                   name="user[name]"
                   value="<%= @user.name %>"
                   autofocus="autofocus">
          </li>

          <li>
            <label>My e-mail address is:</label>
            <input type="email" name="user[email]" value="<%= @user.email %>">
          </li>

          <li>
            <label>My mobile phone number is (optional):</label>
            <input type="text" name="user[phone_number]" value="<%= @user.phone_number %>">
          </li>
        </ul>
      </div>

      <div class="auth-input group">
        <h3 class="auth-h3">Protect your information with a password</h3>
        <ul>
          <li>
            <label>Enter a new password:</label>
            <input type="password" name="user[password]" value="">
          </li>

          <!-- <li>
            <label>Add profile picture or company logo (optional):</label>
            <input type="file" name="user[picture]">
          </li> -->
        </ul>
      </div>

      <button id="new-user-submit" class="sign-up">
        Create account
      </button>
    </fieldset>
  </form>
</main>

<% if !current_user %>
  <section id="new-session-demo-button-section">
    <a id="new-session-demo-button" href="/session/demo" data-method="post">
      Sign in as Demo User to test site
    </a>
  </section>
<% end %>