config/routes.rb
Rails.application.routes.draw do
  root to: "root#root"
  resources :users, only: [:new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  post "session/demo", to: "sessions#demo_user_sign_in"
  resources :queries, only: [:create]
  get "checkout", to: "checkouts#checkout"
  post "checkout/add_address", to: "checkouts#add_address"
  post "checkout/select_address", to: "checkouts#select_address"
  post "checkout/add_card", to: "checkouts#add_card"
  post "checkout/select_card", to: "checkouts#select_card"
  post "checkout/add_purchased_products", to: "checkouts#add_purchased_products"

  namespace :api, defaults: { format: :json } do
    get "current_user/show", to: "current_users#show"
    post "current_user/update", to: "current_users#update"
    get "current_user/cart", to: "current_users#cart"
    get "current_user/products", to: "current_users#products"
    get "current_user/purchased_products", to: "current_users#purchased_products"
    get "current_user/addresses", to: "current_users#addresses"
    get "current_user/current_address", to: "current_users#current_address"
    get "current_user/cards", to: "current_users#cards"
    resources :users, only: [:index, :show] do
      resources :products, only: [:new, :create, :show] do
        resources :reviews, only: [:index, :show, :new, :create]
      end
    end
    resources :queries, only: [:index]
    resources :cart_products, only: [:show, :index]
    post "/cart_products/add/:product_id", to: "cart_products#add_to_cart"
    delete "/cart_products/del/:product_id", to: "cart_products#delete_from_cart"
    patch "/cart_products/qty/:product_id", to: "cart_products#update_quantity"
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def root
    session[:guest_token] ||= SecureRandom.urlsafe_base64(24)
    Cart.create({session_token: session[:guest_token]})

    if current_user
      if !Cart.find_by(buyer_id: current_user.id)
        @cart = Cart.find_by(session_token: session[:guest_token])
      else
        @cart = Cart.find_by(buyer_id: current_user.id)
      end
    end

    if @cart
      @cart.update_attributes({
        buyer_id: current_user.id,
        session_token: session[:user_token]
      })
    end

    @guest_cart = Cart.find_by(session_token: session[:guest_token])
    if @guest_cart && @cart
      @cart.products += @guest_cart.products
      @guest_cart.cart_products.each do |g_cart_prod|
        overlap = @cart.cart_products.find_by({
          product_id: g_cart_prod.product_id
        })
        if overlap
          overlap.update_attributes({
            quantity: g_cart_prod.quantity
          })
        end
      end

      @guest_cart.destroy
    end
  end
end

app/views/root/root.html.erb
<header class="root-header">
  <section class="top">
      <div id="logo-block">
        <a href="/">
          <img class="logo"
               src="<%= image_url("hippolyta_logo_white.png") %>"
               alt="hippolyta logo" />
        </a>
      </div>

      <div id="search-block">
        <form action="<%= queries_url %>" method="post">
          <%= authenticity_token %>
          <ul>
            <li id="search-label">
              Search
            </li>
            <li>
              <input id="query"
                     type="text"
                     name="query[keywords]"
                     value=""
                     autofocus="autofocus">
            </li>
            <li>
              <button id="search-button">
                <img src="<%= image_url("seed/root_page/search-button.png") %>"
                     alt="Go" />
              </button>
            </li>
          </ul>
        </form>
      </div>
  </section>

  <section class="bottom">
    <div id="left">

    </div>
    <% if signed_in? %>
      <div id="middle">
        <a id="hippolyta" href="#current_user/profile">
          <%= current_user.name %>'s Hippolyta.us
        </a>

        <% if last_query %>
          <a id="recent-search" href="/#search_results">
            Most recent search
          </a>
        <% end %>
      </div>

      <div id="right">
        <ul>
          <li>
            <ul id="account-drop-down-ul">
              <li>
                <a id="account" href="<%= session_url %>" data-method="delete">
                  <span id="top-line">Your Account</span>
                  <br>
                  <span>Sign Out? <div id="down-arrow"></div></span>
                </a>
              </li>
              <li id="account-drop-down">
                <ul>
                  <li>
                    <button class="drop-down-button">
                      <a href="<%= session_url %>" data-method="delete">
                        Sign Out
                      </a>
                    </button>
                  </li>
                  <li id="after-button">
                    Want to view
                    <a href="#current_user/profile">
                      your account?
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
    <% else %>
      <div id="middle">
          <a id="hippolyta" href="<%= new_session_url %>">
            Your Hippolyta.us
          </a>

          <% if last_query %>
            <a id="recent-search" href="/#search_results">
              Most recent search
            </a>
          <% end %>
      </div>

      <div id="right">
        <ul>
          <li>
            <ul id="account-drop-down-ul">
              <li>
                <a id="account" href="<%= new_session_url %>">
                  <span id="top-line">Hello. Sign in</span>
                  <br>
                  <span>Your Account <div id="down-arrow"></div></span>
                </a>
              </li>
              <li id="account-drop-down">
                <ul>
                  <li>
                    <button class="drop-down-button">
                      <a href="<%= new_session_url %>">
                        Sign in
                      </a>
                    </button>
                  </li>
                  <li id="after-button">
                    New customer?
                    <a href="<%= new_user_url %>">
                      Start here.
                    </a>
                  </li>
                  <li id="drop-down-demo-button">
                    <a href="/session/demo" data-method="post">
                      Sign in as Demo User to test site
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
    <% end %>
          <li>
            <ul id="cart-drop-down-ul">
              <li>
                <a id="cart" href="#cart">
                  <div id="quantity"><%= current_cart.quantity %></div>
                  <img src="<%= image_url("cart.png") %>" alt="cart" />
                  <span>Cart <div id="down-arrow"></div></span>
                </a>
              </li>
              <li id="cart-drop-down">
                <ul>
                  <% if current_cart.products.empty? %>
                    <li id="cart-empty">
                      Your Cart is empty.
                    </li>
                  <% else %>
                    <% current_cart.cart_products.each do |cart_product| %>
                      <% product = cart_product.product %>
                      <li class="cart-item">
                        <a class="group"
                           href="#sellers/<%= product.seller_id %>/products/<%= product.id %>">
                          <img class="product-image"
                               src="<%= product.picture.url(:thumb) %>"
                               alt="product image" />
                          <ul class="product-info">
                            <li class="product-name">
                              <%= product.name %>
                            </li>
                            <li class="product-price">
                              $<%= money_string(product.sale_price * cart_product.quantity) %>
                            </li>
                            <li class="product-quantity">
                              Quantity: <%= cart_product.quantity %>
                            </li>
                          </ul>
                        </a>
                      </li>
                    <% end %>
                    <li id="cart-total">
                      Total:
                      <span id="total-money-string">
                        $<%= money_string(current_cart.total) %>
                      </span>
                    </li>
                  <% end %>
                  <li>
                    <button class="drop-down-button">
                      <% if current_cart.products.empty? %>
                        <a href="/#cart">
                          View Cart
                        </a>
                      <% else %>
                        <a href="/checkout#checkout">
                          Proceed to checkout
                        </a>
                      <% end %>
                    </button>
                  </li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </div>
  </section>
</header>

<main>
  <div id="content">
    <section class="large-ad">
      <img src="<%= image_url("seed/root_page/Baby-Hippopotamus-Gregor-Berlin-Zoo.jpg") %>"
           alt="picture"/>
    </section>

    <% if !current_user %>
      <section id="demo-button-section">
        <a id="demo-button" href="/session/demo" data-method="post">
          Sign in as Demo User to test site
        </a>
      </section>
    <% end %>
  </div>
</main>

<script type="text/javascript" charset="utf-8">
  $(Hippolyta.initialize);
</script>